name: Simple Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Oplijsten
        run: |
          ls -a
      - uses: docker://pandoc/latex:latest
        with:
          args: "--output=test.pdf README.md" # gets appended to pandoc command
      - name: Copy output
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: test.pdf
      - name: Oplijsten2
        run: |
          ls -a
      - name: GIT commit and push docs
        env: 
          CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "pandect@users.noreply.github.com"
          git add docs
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
